# Generated by Django 5.1.4 on 2026-09-28 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_condicoes_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('pac_nome', models.CharField(max_length=150)),
                ('vet_usuario_id', models.UUIDField(blank=True, null=True)),
                ('vet_nome', models.CharField(blank=True, max_length=150)),
                ('vet_crmv', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitidos', to='documentos.modelodocumento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
