# Generated by Django 5.1.4 on 2026-09-23 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('acao', models.CharField(choices=[('login_ok', 'Login'), ('criar', 'Criou'), ('atualizar', 'Atualizou'), ('excluir', 'Excluiu'), ('exportar', 'Exportou')], max_length=30)),
                ('entidade', models.CharField(choices=[('tutor', 'Tutor'), ('paciente', 'Paciente'), ('insumo', 'Insumo'), ('auth', 'Autenticação')], max_length=30)),
                ('entidade_id', models.UUIDField(blank=True, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=300)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
