# Generated by Django 5.1.4 on 2026-09-27 21:26

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=250, verbose_name='Endereço')),
                ('marca_dagua', models.ImageField(blank=True, help_text='PNG com fundo transparente fica melhor. Sai bem clara no fundo do PDF e pequena no cabeçalho.', null=True, storage=apps.core.storage.TenantFileSystemStorage(), upload_to='clinica/', validators=[apps.core.validators.TamanhoArquivoValidator(2097152, "Marca d'água")], verbose_name="Marca d'água / logo")),
                ('validade_orcamento_dias', models.PositiveSmallIntegerField(default=15, verbose_name='Validade padrão do orçamento (dias)')),
            ],
        ),
    ]
