# Generated by Django 5.1.4 on 2026-09-28 15:57

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_configuracao_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.UUIDField(unique=True)),
                ('nome_completo', models.CharField(blank=True, help_text='Como deve sair na assinatura.', max_length=150)),
                ('crmv', models.CharField(blank=True, max_length=20, verbose_name='CRMV')),
                ('crmv_uf', models.CharField(blank=True, max_length=2, verbose_name='UF do CRMV')),
                ('assinatura', models.ImageField(blank=True, help_text='Imagem PNG (de preferência com fundo transparente) da assinatura ou carimbo.', null=True, storage=apps.core.storage.TenantFileSystemStorage(), upload_to='assinaturas/', validators=[apps.core.validators.TamanhoArquivoValidator(2097152, 'Assinatura')], verbose_name='Assinatura / carimbo')),
            ],
        ),
    ]
