# Generated by Django 5.1.4 on 2026-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoclinica',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cfop_venda',
            field=models.CharField(default='5102', max_length=4, verbose_name='CFOP — produto normal'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cfop_venda_st',
            field=models.CharField(default='5405', max_length=4, verbose_name='CFOP — produto com substituição tributária'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cst_csosn_venda',
            field=models.CharField(default='102', max_length=4, verbose_name='CSOSN/CST — produto normal'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cst_csosn_venda_st',
            field=models.CharField(default='500', max_length=4, verbose_name='CSOSN/CST — produto com substituição tributária'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='regime_tributario',
            field=models.CharField(choices=[('simples', 'Simples Nacional'), ('mei', 'MEI'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=10, verbose_name='Regime tributário'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='configuracaoclinica',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, verbose_name='Rua'),
        ),
    ]
