# Generated by Django 5.1.4 on 2026-10-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaoclinica_bairro_configuracaoclinica_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de contato'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
