# Generated by Django 5.1.4 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_contato_endereco_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='mapa',
            field=models.CharField(blank=True, max_length=30, verbose_name='Registro no MAPA'),
        ),
    ]
