# Generated by Django 5.1.4 on 2026-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_loginaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioclinica',
            name='papel',
            field=models.CharField(choices=[('admin', 'Admin'), ('vet', 'Veterinária/o'), ('atendente', 'Atendente administrativo'), ('motorista', 'Motorista')], default='vet', max_length=10),
        ),
    ]
