# Generated by Django 5.1.4 on 2026-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_usuarioclinica_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='modulo_agenda',
            field=models.BooleanField(default=True, verbose_name='Agenda'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_atendimentos',
            field=models.BooleanField(default=True, verbose_name='Atendimentos'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_estoque',
            field=models.BooleanField(default=True, verbose_name='Estoque'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_financeiro',
            field=models.BooleanField(default=True, verbose_name='Serviços/Financeiro'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_pacientes',
            field=models.BooleanField(default=True, verbose_name='Pacientes'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_tutores',
            field=models.BooleanField(default=True, verbose_name='Tutores'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='modulo_whatsapp_lembrete',
            field=models.BooleanField(default=False, verbose_name='Lembrete de WhatsApp (Agenda)'),
        ),
    ]
