# Generated by Django 5.1.4 on 2026-09-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_clinica_modulo_agenda_clinica_modulo_atendimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='trocar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
