# Generated by Django 5.1.4 on 2026-09-23 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('codigo_barras', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('unidades_por_pacote', models.PositiveIntegerField(default=1)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('ncm', models.CharField(blank=True, help_text='Preenchido automaticamente ao importar XML de NF-e do fornecedor.', max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=4, verbose_name='CFOP')),
                ('cst_csosn', models.CharField(blank=True, max_length=4, verbose_name='CST/CSOSN')),
                ('tipo_fiscal', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=10)),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SD1', 'Entrada (SD1)'), ('SD2', 'Saída (SD2)'), ('SD3', 'Interno (SD3)')], max_length=3)),
                ('subtipo', models.CharField(choices=[('nfe_fornecedor', 'NF-e do fornecedor'), ('manual_sem_nota', 'Manual sem nota fiscal'), ('venda_servico', 'Venda/consumo em serviço'), ('venda_produto', 'Venda de produto'), ('consumo_atendimento', 'Consumo em atendimento'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('perda', 'Perda')], max_length=30)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem_tipo', models.CharField(blank=True, max_length=30)),
                ('origem_id', models.UUIDField(blank=True, null=True)),
                ('nota_fiscal_chave', models.CharField(blank=True, max_length=44)),
                ('nota_fiscal_numero', models.CharField(blank=True, max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.insumo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
