# Generated by Django 5.1.4 on 2026-09-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='subtipo',
            field=models.CharField(choices=[('nfe_fornecedor', 'NF-e do fornecedor'), ('manual_sem_nota', 'Manual sem nota fiscal'), ('venda_servico', 'Venda/consumo em serviço'), ('venda_produto', 'Venda de produto'), ('consumo_atendimento', 'Consumo em atendimento'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('perda', 'Perda'), ('estorno_consumo', 'Estorno de consumo')], max_length=30),
        ),
    ]
