# Generated by Django 5.1.4 on 2026-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_subtipo_estorno_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='origem',
            field=models.CharField(choices=[('0', '0 — Nacional'), ('1', '1 — Estrangeira, importação direta'), ('2', '2 — Estrangeira, adquirida no mercado interno'), ('3', '3 — Nacional, conteúdo de importação acima de 40%'), ('4', '4 — Nacional, produção conforme processos básicos'), ('5', '5 — Nacional, conteúdo de importação até 40%'), ('6', '6 — Estrangeira, importação direta, sem similar nacional'), ('7', '7 — Estrangeira, mercado interno, sem similar nacional'), ('8', '8 — Nacional, conteúdo de importação acima de 70%')], default='0', max_length=1, verbose_name='Origem da mercadoria'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tem_st',
            field=models.BooleanField(default=False, help_text='Marcado sozinho ao importar o XML do fornecedor quando o ICMS já veio recolhido.', verbose_name='Substituição tributária (ICMS-ST)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cfop',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar a regra fiscal da clínica.', max_length=4, verbose_name='CFOP (exceção)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cst_csosn',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar a regra fiscal da clínica.', max_length=4, verbose_name='CST/CSOSN (exceção)'),
        ),
    ]
