# Generated by Django 5.1.4 on 2026-09-30 17:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_insumo_origem_insumo_tem_st_alter_insumo_cfop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='embalagem',
            field=models.CharField(blank=True, help_text='Ex.: "caixa", "frasco", "pacote".', max_length=30, verbose_name='Embalagem de compra'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Na unidade de uso. Em branco = regra geral (menos de 3).', max_digits=12, null=True, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidade',
            field=models.CharField(choices=[('un', 'unidade'), ('ml', 'ml'), ('g', 'g'), ('comp', 'comprimido'), ('caps', 'cápsula'), ('dose', 'dose'), ('amp', 'ampola'), ('par', 'par'), ('kg', 'kg'), ('L', 'litro'), ('cm', 'cm')], default='un', max_length=5, verbose_name='Unidade de uso'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='qtd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidades_por_pacote',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantas unidades de uso vêm em uma embalagem (ex.: 100 seringas, 50 ml).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Conteúdo da embalagem'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por unidade de uso'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Por unidade de uso.', max_digits=12, null=True),
        ),
    ]
