services:
  - type: web
    name: vettro
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vettro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRA_HORAS
        value: "8"
      - key: CORS_ORIGINS
        value: "*"
      - key: ADMIN_NOME
        value: Administrador
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SENHA
        sync: false

databases:
  - name: vettro-db
    plan: starter
    databaseName: vettro
    user: vettro
