# Generated by Django 5.1.4 on 2026-09-28 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=150, verbose_name='Cliente (opcional)')),
                ('itens', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_tipo', models.CharField(blank=True, choices=[('valor', 'R$'), ('percentual', '%')], max_length=10)),
                ('desconto_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('desconto_motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo do desconto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito')], max_length=10)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_por_nome', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
