# Generated by Django 5.1.4 on 2026-09-27 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_condicoes_padrao'),
        ('tutores', '0003_tutor_tel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('tutor_nome', models.CharField(max_length=150)),
                ('tutor_tel', models.CharField(blank=True, max_length=20)),
                ('pac_nome', models.CharField(blank=True, max_length=150)),
                ('itens', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valido_ate', models.DateField()),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='pacientes.paciente')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='tutores.tutor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
