"""initial schema

Revision ID: 59fcc1bdd6bd
Revises: 
Create Date: 2026-09-10 17:27:27.997985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59fcc1bdd6bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cirurgias_cat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('valor_p', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tel', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raca', sa.String(length=120), nullable=True),
    sa.Column('peso', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('idade', sa.String(length=60), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('foto_perfil', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('pac_nome', sa.String(length=200), nullable=False),
    sa.Column('tutor_nome', sa.String(length=200), nullable=True),
    sa.Column('tutor_tel', sa.String(length=40), nullable=True),
    sa.Column('queixa', sa.Text(), nullable=True),
    sa.Column('servicos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('servicos_livre', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamnese_hist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('hora', sa.Time(), server_default=sa.text('CURRENT_TIME'), nullable=False),
    sa.Column('queixa', sa.Text(), nullable=True),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('alergias', sa.String(length=300), nullable=True),
    sa.Column('obs_add', sa.Text(), nullable=True),
    sa.Column('alimentacao', sa.String(length=60), nullable=True),
    sa.Column('vacina', sa.String(length=30), nullable=True),
    sa.Column('verme', sa.String(length=30), nullable=True),
    sa.Column('rua', sa.String(length=20), nullable=True),
    sa.Column('convive', sa.String(length=10), nullable=True),
    sa.Column('av_fc', sa.String(length=20), nullable=True),
    sa.Column('av_fr', sa.String(length=20), nullable=True),
    sa.Column('av_pa', sa.String(length=20), nullable=True),
    sa.Column('av_temp', sa.String(length=20), nullable=True),
    sa.Column('av_hidratacao', sa.String(length=60), nullable=True),
    sa.Column('av_mucosas', sa.String(length=60), nullable=True),
    sa.Column('av_linf_sub', sa.String(length=60), nullable=True),
    sa.Column('av_linf_sube', sa.String(length=60), nullable=True),
    sa.Column('av_linf_ing', sa.String(length=60), nullable=True),
    sa.Column('av_linf_pop', sa.String(length=60), nullable=True),
    sa.Column('av_demais', sa.Text(), nullable=True),
    sa.Column('servicos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insumos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plantao', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('pac_nome', sa.String(length=200), nullable=False),
    sa.Column('pac_especie', sa.String(length=50), nullable=True),
    sa.Column('tutor_nome', sa.String(length=200), nullable=True),
    sa.Column('tutor_tel', sa.String(length=40), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('servicos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insumos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plantao', sa.Boolean(), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cirurgias_hist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('hora', sa.Time(), server_default=sa.text('CURRENT_TIME'), nullable=False),
    sa.Column('proc', sa.String(length=200), nullable=False),
    sa.Column('clinica', sa.String(length=200), nullable=True),
    sa.Column('anestesista', sa.String(length=200), nullable=True),
    sa.Column('procedimentos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insumos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plantao', sa.Boolean(), nullable=False),
    sa.Column('outra_cidade', sa.Boolean(), nullable=False),
    sa.Column('desc_cir', sa.Text(), nullable=True),
    sa.Column('pos_op', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobrancas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('servicos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insumos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tutor_nome', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('fotos')
    op.drop_table('exames')
    op.drop_table('cobrancas')
    op.drop_table('cirurgias_hist')
    op.drop_table('atendimentos')
    op.drop_table('anamnese_hist')
    op.drop_table('agendamentos')
    op.drop_table('pacientes')
    op.drop_table('usuarios')
    op.drop_table('tutores')
    op.drop_table('servicos')
    op.drop_table('insumos')
    op.drop_table('cirurgias_cat')
    # ### end Alembic commands ###
