"""adiciona codigo de barras em insumos

Revision ID: 5a3f82b1ff7e
Revises: 9a246ba8ea1c
Create Date: 2026-09-18 15:13:19.566470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3f82b1ff7e'
down_revision: Union[str, None] = '9a246ba8ea1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumos', sa.Column('codigo_barras', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'insumos', ['codigo_barras'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insumos', type_='unique')
    op.drop_column('insumos', 'codigo_barras')
    # ### end Alembic commands ###
