"""troca idade por data_nascimento em pacientes

Revision ID: 704815a5f10d
Revises: 59fcc1bdd6bd
Create Date: 2026-09-18 14:14:26.453465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704815a5f10d'
down_revision: Union[str, None] = '59fcc1bdd6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.drop_column('pacientes', 'idade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('idade', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('pacientes', 'data_nascimento')
    # ### end Alembic commands ###
