"""adiciona como_conheceu em tutores

Revision ID: 73b9934d31de
Revises: 704815a5f10d
Create Date: 2026-09-18 14:33:30.622535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b9934d31de'
down_revision: Union[str, None] = '704815a5f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutores', sa.Column('como_conheceu', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutores', 'como_conheceu')
    # ### end Alembic commands ###
