"""adiciona unidades por pacote em insumos

Revision ID: 8178741d89eb
Revises: 5a3f82b1ff7e
Create Date: 2026-09-18 15:18:50.083315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8178741d89eb'
down_revision: Union[str, None] = '5a3f82b1ff7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumos', sa.Column('unidades_por_pacote', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumos', 'unidades_por_pacote')
    # ### end Alembic commands ###
