"""adiciona consentimento LGPD em tutores e tabela de auditoria

Revision ID: 9a246ba8ea1c
Revises: a987ffa15eb6
Create Date: 2026-09-18 14:58:11.530463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a246ba8ea1c'
down_revision: Union[str, None] = 'a987ffa15eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=200), nullable=True),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('entidade', sa.String(length=30), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('detalhe', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tutores', sa.Column('consentimento_dados', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tutores', sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutores', 'consentimento_em')
    op.drop_column('tutores', 'consentimento_dados')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
