"""estrutura endereco de tutores com cep numero complemento bairro cidade uf

Revision ID: a987ffa15eb6
Revises: 73b9934d31de
Create Date: 2026-09-18 14:34:26.410605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a987ffa15eb6'
down_revision: Union[str, None] = '73b9934d31de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutores', sa.Column('cep', sa.String(length=9), nullable=True))
    op.add_column('tutores', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('tutores', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('tutores', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('tutores', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('tutores', sa.Column('uf', sa.String(length=2), nullable=True))
    op.alter_column('tutores', 'endereco',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutores', 'endereco',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tutores', 'uf')
    op.drop_column('tutores', 'cidade')
    op.drop_column('tutores', 'bairro')
    op.drop_column('tutores', 'complemento')
    op.drop_column('tutores', 'numero')
    op.drop_column('tutores', 'cep')
    # ### end Alembic commands ###
