# Generated by Django 5.1.4 on 2026-09-23 19:28

import apps.core.storage
import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=10)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('foto_perfil', models.ImageField(blank=True, null=True, storage=apps.core.storage.TenantFileSystemStorage(), upload_to='pacientes/fotos_perfil/', validators=[apps.core.validators.TamanhoArquivoValidator(3145728, 'Foto de perfil')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='tutores.tutor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
