# Generated by Django 5.1.4 on 2026-09-23 19:41

import apps.core.storage
import apps.core.validators
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseHist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time)),
                ('queixa', models.TextField(blank=True, verbose_name='Queixa principal')),
                ('historico', models.TextField(blank=True, verbose_name='Histórico clínico anterior')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conhecidas')),
                ('obs_add', models.TextField(blank=True, verbose_name='Observações adicionais')),
                ('alimentacao', models.CharField(blank=True, choices=[('racao_seca', 'Ração seca'), ('racao_umida', 'Ração úmida'), ('mista', 'Mista'), ('natural', 'Natural'), ('outro', 'Outro')], max_length=20)),
                ('vacina', models.CharField(blank=True, choices=[('em_dia', 'Em dia'), ('atrasada', 'Atrasada'), ('nao', 'Não'), ('desconhecido', 'Desconhecido')], max_length=20, verbose_name='Vacinação')),
                ('verme', models.CharField(blank=True, choices=[('em_dia', 'Em dia'), ('atrasada', 'Atrasada'), ('nao', 'Não'), ('desconhecido', 'Desconhecido')], max_length=20, verbose_name='Vermifugação')),
                ('rua', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('controlado', 'Controlado')], max_length=20, verbose_name='Acesso à rua')),
                ('convive', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, verbose_name='Convive com outros animais')),
                ('av_fc', models.CharField(blank=True, max_length=30, verbose_name='FC (bpm)')),
                ('av_fr', models.CharField(blank=True, max_length=30, verbose_name='FR (mpm)')),
                ('av_pa', models.CharField(blank=True, max_length=30, verbose_name='PA (mmHg)')),
                ('av_temp', models.CharField(blank=True, max_length=30, verbose_name='Temperatura (°C)')),
                ('av_hidratacao', models.CharField(blank=True, max_length=60, verbose_name='Hidratação')),
                ('av_mucosas', models.CharField(blank=True, max_length=60, verbose_name='Mucosas')),
                ('av_linf_sub', models.CharField(blank=True, max_length=60, verbose_name='Linfonodos submandibulares')),
                ('av_linf_sube', models.CharField(blank=True, max_length=60, verbose_name='Linfonodos subescapulares')),
                ('av_linf_ing', models.CharField(blank=True, max_length=60, verbose_name='Linfonodos inguinais')),
                ('av_linf_pop', models.CharField(blank=True, max_length=60, verbose_name='Linfonodos poplíteos')),
                ('av_demais', models.TextField(blank=True, verbose_name='Demais informações')),
                ('servicos', models.JSONField(blank=True, default=list)),
                ('insumos', models.JSONField(blank=True, default=list)),
                ('plantao', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CirurgiaHist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time)),
                ('proc', models.CharField(max_length=200, verbose_name='Procedimento')),
                ('clinica', models.CharField(blank=True, max_length=150, verbose_name='Clínica/local')),
                ('anestesista', models.CharField(blank=True, max_length=150)),
                ('desc_cir', models.TextField(blank=True, verbose_name='Descrição da cirurgia')),
                ('pos_op', models.TextField(blank=True, verbose_name='Pós-operatório')),
                ('procedimentos', models.JSONField(blank=True, default=list)),
                ('insumos', models.JSONField(blank=True, default=list)),
                ('plantao', models.BooleanField(default=False)),
                ('outra_cidade', models.BooleanField(default=False, verbose_name='Deslocamento (outra cidade)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Cirurgias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(storage=apps.core.storage.TenantFileSystemStorage(), upload_to='pacientes/exames/', validators=[apps.core.validators.TamanhoArquivoValidator(5242880, 'Exame')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(storage=apps.core.storage.TenantFileSystemStorage(), upload_to='pacientes/fotos/', validators=[apps.core.validators.TamanhoArquivoValidator(4194304, 'Foto')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
