# Generated by Django 5.1.4 on 2026-09-27 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_anamnesehist_cirurgiahist_exame_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='condicoes',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.condicaoclinica'),
        ),
    ]
