# Generated by Django 5.1.4 on 2026-10-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_tipos_medicacao_curativo'),
        ('pacientes', '0004_condicoes_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='atendimentos.atendimento'),
        ),
        migrations.AddField(
            model_name='foto',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='atendimentos.atendimento'),
        ),
    ]
