# Generated by Django 5.1.4 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_exame_foto_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=6),
        ),
    ]
