# Generated by Django 5.1.4 on 2026-09-28 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_condicoes_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('livre', 'Receita livre'), ('simples', 'Receita simples'), ('controlada', 'Receita controlada')], max_length=12)),
                ('texto', models.TextField(blank=True)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('pac_nome', models.CharField(max_length=150)),
                ('pac_especie', models.CharField(blank=True, max_length=20)),
                ('pac_raca', models.CharField(blank=True, max_length=100)),
                ('pac_idade', models.CharField(blank=True, max_length=40)),
                ('pac_peso', models.CharField(blank=True, max_length=20)),
                ('tutor_nome', models.CharField(blank=True, max_length=150)),
                ('tutor_endereco', models.CharField(blank=True, max_length=300)),
                ('vet_usuario_id', models.UUIDField(blank=True, null=True)),
                ('vet_nome', models.CharField(blank=True, max_length=150)),
                ('vet_crmv', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
