# Generated by Django 5.1.4 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pac_sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='tutor_cidade_uf',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='receita',
            name='tutor_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='receita',
            name='tutor_rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receita',
            name='vet_mapa',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
