# Generated by Django 5.1.4 on 2026-09-23 19:41

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_anamnesehist_cirurgiahist_exame_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pac_nome', models.CharField(max_length=150)),
                ('pac_especie', models.CharField(blank=True, max_length=10)),
                ('tutor_nome', models.CharField(blank=True, max_length=150)),
                ('tutor_tel', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time)),
                ('servicos', models.JSONField(blank=True, default=list)),
                ('insumos', models.JSONField(blank=True, default=list)),
                ('plantao', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
