# Generated by Django 5.1.4 on 2026-09-27 21:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_tipo_numero_retorno_de'),
        ('estoque', '0002_subtipo_estorno_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_proxima_dose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dose',
            field=models.CharField(blank=True, choices=[('1', '1ª dose'), ('2', '2ª dose'), ('3', '3ª dose'), ('reforco', 'Reforço anual')], max_length=10),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='vacina_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('ambulatorial', 'Ambulatorial'), ('emergencia', 'Emergência'), ('vacinacao', 'Vacinação')], default='consulta', max_length=15),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(blank=True, choices=[('cao', 'Cão'), ('gato', 'Gato'), ('outro', 'Outro')], help_text='Em branco = qualquer espécie.', max_length=10)),
                ('doses_iniciais', models.PositiveSmallIntegerField(default=1, help_text='Quantas doses no protocolo inicial (1 a 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('intervalo_dias', models.PositiveSmallIntegerField(default=21, help_text='Dias entre as doses do protocolo inicial.')),
                ('reforco_anual', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(blank=True, help_text='Item do estoque que sai quando a vacina é aplicada (1 unidade por dose).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas', to='estoque.insumo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='vacina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to='atendimentos.vacina'),
        ),
    ]
