# Generated by Django 5.1.4 on 2026-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_vacinacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='lembrete_dias_antes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='lembrete_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
