# Generated by Django 5.1.4 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_lembrete_proxima_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
