# Generated by Django 5.1.4 on 2026-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_data_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='dose',
            field=models.CharField(blank=True, choices=[('1', '1ª dose'), ('2', '2ª dose'), ('3', '3ª dose'), ('reforco', 'Anual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('ambulatorial', 'Ambulatorial'), ('emergencia', 'Emergência'), ('vacinacao', 'Vacinação'), ('aplicacao_medicacao', 'Aplicação de medicação'), ('curativo', 'Curativo')], default='consulta', max_length=25),
        ),
    ]
