# Generated by Django 5.1.4 on 2026-09-24 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEmitida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nfse', 'NFS-e (serviço)'), ('nfce', 'NFC-e (produto)')], max_length=4)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('erro', 'Erro na emissão'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('url_pdf', models.URLField(blank=True)),
                ('url_xml', models.URLField(blank=True)),
                ('mensagem_erro', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='financeiro.cobranca')),
            ],
            options={
                'verbose_name': 'Nota fiscal emitida',
                'verbose_name_plural': 'Notas fiscais emitidas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoTEF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('negado', 'Negado'), ('erro', 'Erro de comunicação'), ('cancelado', 'Cancelado')], max_length=20)),
                ('adquirente', models.CharField(blank=True, max_length=60, verbose_name='Adquirente/banco')),
                ('terminal_codigo', models.CharField(blank=True, max_length=30, verbose_name='Código de terminal')),
                ('bandeira', models.CharField(blank=True, max_length=30)),
                ('nsu', models.CharField(blank=True, max_length=40)),
                ('codigo_autorizacao', models.CharField(blank=True, max_length=40)),
                ('mensagem_erro', models.CharField(blank=True, max_length=300)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_tef', to='financeiro.cobranca')),
            ],
            options={
                'verbose_name': 'Transação TEF',
                'verbose_name_plural': 'Transações TEF',
                'ordering': ['-criado_em'],
            },
        ),
    ]
