# Generated by Django 5.1.4 on 2026-10-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_servico_unidade_cobranca'),
        ('pagamentos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalemitida',
            name='dados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notafiscalemitida',
            name='emitida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalemitida',
            name='emitida_por_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='notafiscalemitida',
            name='simulacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notafiscalemitida',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='notafiscalemitida',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='notafiscalemitida',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='financeiro.cobranca'),
        ),
        migrations.AlterField(
            model_name='notafiscalemitida',
            name='mensagem_erro',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
