# Generated by Django 5.1.4 on 2026-09-23 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_anamnesehist_cirurgiahist_exame_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('pac_nome', models.CharField(max_length=150)),
                ('tutor_nome', models.CharField(blank=True, max_length=150)),
                ('tutor_tel', models.CharField(blank=True, max_length=20)),
                ('queixa', models.CharField(blank=True, max_length=300)),
                ('servicos', models.JSONField(blank=True, default=list)),
                ('servicos_livre', models.CharField(blank=True, max_length=300, verbose_name='Outros serviços')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['data', 'hora'],
            },
        ),
    ]
