# Generated by Django 5.1.4 on 2026-09-23 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('turno', models.CharField(choices=[('dia_inteiro', 'Dia inteiro'), ('manha', 'Manhã (até 12h)'), ('tarde', 'Tarde (12h–18h)'), ('noite', 'Noite (a partir das 18h)')], default='dia_inteiro', max_length=15)),
                ('motivo', models.CharField(max_length=200)),
                ('criado_por_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='agenda.consultorio')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agenda.consultorio'),
        ),
    ]
