# Generated by Django 5.1.4 on 2026-09-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_consultorio_bloqueioagenda_agendamento_consultorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='nome',
            field=models.CharField(help_text='Livre — pode ser uma sala, uma unidade, ou o nome de uma profissional (ex: "Consultório Franciele Vet").', max_length=150),
        ),
    ]
