# Generated by Django 5.1.4 on 2026-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_consultorio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido pelo comando enviar_lembretes_whatsapp — evita reenvio duplicado.', null=True),
        ),
    ]
