# Generated by Django 5.1.4 on 2026-09-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_lembrete_enviado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueioagenda',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], help_text='Obrigatório se o bloqueio for recorrente.', null=True, verbose_name='Dia da semana'),
        ),
        migrations.AddField(
            model_name='bloqueioagenda',
            name='recorrente',
            field=models.BooleanField(default=False, verbose_name='Repetir toda semana'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='consultorio',
            field=models.ForeignKey(blank=True, help_text='Em branco = bloqueio geral (fecha a agenda inteira, todos os consultórios).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='agenda.consultorio'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Em branco só é permitido em bloqueio recorrente (sem data de término).', null=True),
        ),
    ]
