# Generated by Django 5.1.4 on 2026-09-23 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_anamnesehist_cirurgiahist_exame_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirurgiaCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('valor_p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Até 10kg')),
                ('valor_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='10–25kg')),
                ('valor_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acima de 25kg')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de cirurgia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_servico_municipal', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicos', models.JSONField(blank=True, default=list)),
                ('insumos', models.JSONField(blank=True, default=list)),
                ('obs', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('tutor_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
