# Generated by Django 5.1.4 on 2026-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_cobranca_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='desconto_informado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='O que foi digitado: reais ou percentual, conforme desconto_tipo.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='desconto_motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo do desconto'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='desconto_tipo',
            field=models.CharField(blank=True, choices=[('valor', 'R$'), ('percentual', '%')], max_length=10),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='pago_por_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
