# Generated by Django 5.1.4 on 2026-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_cobranca_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='unidade_cobranca',
            field=models.CharField(blank=True, help_text='Ex.: "hora", "diária", "sessão". Em branco = por vez.', max_length=20, verbose_name='Cobrado por'),
        ),
    ]
