# Generated by Django 5.1.4 on 2026-09-23 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('como_conheceu', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('radio', 'Rádio'), ('tv', 'TV'), ('google', 'Google'), ('outro', 'Outro')], max_length=30)),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('consentimento_dados', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('consentimento_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
