# Generated by Django 5.1.4 on 2026-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='consentimento_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Consentimento p/ lembrete de WhatsApp'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='consentimento_whatsapp_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
