# Generated by Django 5.1.4 on 2026-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0002_tutor_consentimento_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tel2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Outro telefone'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
    ]
