# Generated by Django 5.1.4 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0003_tutor_tel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
    ]
